// flow-typed signature: cbe10c7840b26ca7711090534e6abb87
// flow-typed version: <<STUB>>/@fortawesome/fontawesome-free-brands_v5.0.13/flow_v0.99.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@fortawesome/fontawesome-free-brands'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@fortawesome/fontawesome-free-brands' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@fortawesome/fontawesome-free-brands/fa500px' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAccessibleIcon' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAccusoft' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAdn' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAdversal' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAffiliatetheme' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAlgolia' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAmazon' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAmazonPay' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAmilia' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAndroid' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAngellist' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAngrycreative' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAngular' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faApper' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faApple' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faApplePay' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAppStore' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAppStoreIos' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAsymmetrik' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAudible' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAutoprefixer' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAvianex' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAviato' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faAws' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBandcamp' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBehance' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBehanceSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBimobject' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBitbucket' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBitcoin' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBity' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBlackberry' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBlackTie' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBlogger' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBloggerB' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBluetooth' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBluetoothB' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBtc' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBuromobelexperte' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faBuysellads' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcAmazonPay' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcAmex' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcApplePay' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcDinersClub' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcDiscover' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcJcb' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcMastercard' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcPaypal' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcStripe' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCcVisa' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCentercode' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faChrome' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCloudscale' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCloudsmith' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCloudversify' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCodepen' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCodiepie' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faConnectdevelop' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faContao' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCpanel' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommons' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsBy' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsNc' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsNcEu' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsNcJp' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsNd' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsPd' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsPdAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsRemix' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsSa' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsSampling' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsSamplingPlus' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsShare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCss3' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCss3Alt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faCuttlefish' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDAndD' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDashcube' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDelicious' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDeploydog' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDeskpro' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDeviantart' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDigg' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDigitalOcean' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDiscord' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDiscourse' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDochub' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDocker' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDraft2digital' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDribbble' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDribbbleSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDropbox' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDrupal' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faDyalog' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faEarlybirds' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faEbay' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faEdge' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faElementor' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faEmber' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faEmpire' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faEnvira' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faErlang' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faEthereum' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faEtsy' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faExpeditedssl' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFacebook' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFacebookF' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFacebookMessenger' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFacebookSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFirefox' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFirstdraft' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFirstOrder' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFirstOrderAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFlickr' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFlipboard' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFly' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFontAwesome' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFontAwesomeAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFontAwesomeFlag' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFontAwesomeLogoFull' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFonticons' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFonticonsFi' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFortAwesome' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFortAwesomeAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faForumbee' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFoursquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFreebsd' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFreeCodeCamp' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faFulcrum' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGalacticRepublic' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGalacticSenate' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGetPocket' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGg' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGgCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGit' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGithub' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGithubAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGithubSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGitkraken' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGitlab' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGitSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGitter' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGlide' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGlideG' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGofore' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGoodreads' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGoodreadsG' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGoogle' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGoogleDrive' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGooglePlay' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGooglePlus' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGooglePlusG' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGooglePlusSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGoogleWallet' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGratipay' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGrav' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGripfire' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGrunt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faGulp' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faHackerNews' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faHackerNewsSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faHips' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faHireAHelper' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faHooli' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faHotjar' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faHouzz' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faHtml5' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faHubspot' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faImdb' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faInstagram' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faInternetExplorer' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faIoxhost' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faItunes' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faItunesNote' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faJava' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faJediOrder' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faJenkins' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faJoget' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faJoomla' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faJs' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faJsfiddle' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faJsSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faKeybase' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faKeycdn' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faKickstarter' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faKickstarterK' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faKorvue' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLaravel' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLastfm' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLastfmSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLeanpub' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLess' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLine' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLinkedin' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLinkedinIn' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLinode' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLinux' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faLyft' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMagento' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMandalorian' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMastodon' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMaxcdn' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMedapps' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMedium' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMediumM' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMedrt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMeetup' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMicrosoft' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMix' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMixcloud' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMizuni' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faModx' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faMonero' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faNapster' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faNintendoSwitch' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faNode' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faNodeJs' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faNpm' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faNs8' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faNutritionix' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faOdnoklassniki' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faOdnoklassnikiSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faOldRepublic' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faOpencart' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faOpenid' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faOpera' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faOptinMonster' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faOsi' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPage4' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPagelines' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPalfed' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPatreon' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPaypal' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPeriscope' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPhabricator' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPhoenixFramework' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPhoenixSquadron' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPhp' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPiedPiper' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPiedPiperAlt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPiedPiperHat' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPiedPiperPp' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPinterest' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPinterestP' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPinterestSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPlaystation' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faProductHunt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPushed' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faPython' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faQq' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faQuinscape' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faQuora' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRavelry' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faReact' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faReadme' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRebel' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faReddit' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRedditAlien' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRedditSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRedRiver' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRendact' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRenren' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faReplyd' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faResearchgate' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faResolving' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRocketchat' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRockrms' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faRProject' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSafari' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSass' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSchlix' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faScribd' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSearchengin' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSellcast' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSellsy' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faServicestack' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faShirtsinbulk' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSimplybuilt' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSistrix' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSith' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSkyatlas' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSkype' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSlack' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSlackHash' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSlideshare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSnapchat' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSnapchatGhost' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSnapchatSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSoundcloud' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSpeakap' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSpotify' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStackExchange' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStackOverflow' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStaylinked' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSteam' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSteamSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSteamSymbol' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStickerMule' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStrava' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStripe' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStripeS' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStudiovinari' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStumbleupon' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faStumbleuponCircle' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSuperpowers' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faSupple' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTeamspeak' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTelegram' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTelegramPlane' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTencentWeibo' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faThemeisle' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTradeFederation' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTrello' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTripadvisor' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTumblr' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTumblrSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTwitch' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTwitter' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTwitterSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faTypo3' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faUber' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faUikit' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faUniregistry' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faUntappd' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faUsb' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faUssunnah' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faVaadin' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faViacoin' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faViadeo' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faViadeoSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faViber' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faVimeo' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faVimeoSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faVimeoV' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faVine' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faVk' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faVnv' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faVuejs' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWeibo' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWeixin' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWhatsapp' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWhatsappSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWhmcs' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWikipediaW' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWindows' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWolfPackBattalion' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWordpress' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWordpressSimple' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWpbeginner' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWpexplorer' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faWpforms' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faXbox' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faXing' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faXingSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faYahoo' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faYandex' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faYandexInternational' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faYCombinator' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faYelp' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faYoast' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faYoutube' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/faYoutubeSquare' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/index.es' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/shakable.es' {
  declare module.exports: any;
}

declare module '@fortawesome/fontawesome-free-brands/shakable' {
  declare module.exports: any;
}

// Filename aliases
declare module '@fortawesome/fontawesome-free-brands/fa500px.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/fa500px'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAccessibleIcon.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAccessibleIcon'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAccusoft.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAccusoft'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAdn.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAdn'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAdversal.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAdversal'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAffiliatetheme.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAffiliatetheme'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAlgolia.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAlgolia'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAmazon.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAmazon'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAmazonPay.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAmazonPay'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAmilia.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAmilia'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAndroid.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAndroid'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAngellist.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAngellist'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAngrycreative.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAngrycreative'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAngular.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAngular'>;
}
declare module '@fortawesome/fontawesome-free-brands/faApper.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faApper'>;
}
declare module '@fortawesome/fontawesome-free-brands/faApple.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faApple'>;
}
declare module '@fortawesome/fontawesome-free-brands/faApplePay.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faApplePay'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAppStore.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAppStore'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAppStoreIos.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAppStoreIos'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAsymmetrik.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAsymmetrik'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAudible.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAudible'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAutoprefixer.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAutoprefixer'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAvianex.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAvianex'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAviato.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAviato'>;
}
declare module '@fortawesome/fontawesome-free-brands/faAws.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faAws'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBandcamp.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBandcamp'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBehance.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBehance'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBehanceSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBehanceSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBimobject.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBimobject'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBitbucket.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBitbucket'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBitcoin.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBitcoin'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBity.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBity'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBlackberry.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBlackberry'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBlackTie.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBlackTie'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBlogger.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBlogger'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBloggerB.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBloggerB'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBluetooth.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBluetooth'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBluetoothB.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBluetoothB'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBtc.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBtc'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBuromobelexperte.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBuromobelexperte'>;
}
declare module '@fortawesome/fontawesome-free-brands/faBuysellads.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faBuysellads'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcAmazonPay.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcAmazonPay'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcAmex.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcAmex'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcApplePay.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcApplePay'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcDinersClub.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcDinersClub'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcDiscover.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcDiscover'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcJcb.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcJcb'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcMastercard.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcMastercard'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcPaypal.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcPaypal'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcStripe.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcStripe'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCcVisa.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCcVisa'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCentercode.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCentercode'>;
}
declare module '@fortawesome/fontawesome-free-brands/faChrome.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faChrome'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCloudscale.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCloudscale'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCloudsmith.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCloudsmith'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCloudversify.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCloudversify'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCodepen.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCodepen'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCodiepie.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCodiepie'>;
}
declare module '@fortawesome/fontawesome-free-brands/faConnectdevelop.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faConnectdevelop'>;
}
declare module '@fortawesome/fontawesome-free-brands/faContao.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faContao'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCpanel.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCpanel'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommons.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommons'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsBy.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsBy'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsNc.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsNc'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsNcEu.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsNcEu'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsNcJp.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsNcJp'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsNd.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsNd'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsPd.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsPd'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsPdAlt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsPdAlt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsRemix.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsRemix'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsSa.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsSa'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsSampling.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsSampling'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsSamplingPlus.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsSamplingPlus'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCreativeCommonsShare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCreativeCommonsShare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCss3.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCss3'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCss3Alt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCss3Alt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faCuttlefish.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faCuttlefish'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDAndD.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDAndD'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDashcube.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDashcube'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDelicious.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDelicious'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDeploydog.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDeploydog'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDeskpro.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDeskpro'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDeviantart.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDeviantart'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDigg.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDigg'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDigitalOcean.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDigitalOcean'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDiscord.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDiscord'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDiscourse.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDiscourse'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDochub.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDochub'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDocker.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDocker'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDraft2digital.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDraft2digital'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDribbble.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDribbble'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDribbbleSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDribbbleSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDropbox.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDropbox'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDrupal.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDrupal'>;
}
declare module '@fortawesome/fontawesome-free-brands/faDyalog.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faDyalog'>;
}
declare module '@fortawesome/fontawesome-free-brands/faEarlybirds.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faEarlybirds'>;
}
declare module '@fortawesome/fontawesome-free-brands/faEbay.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faEbay'>;
}
declare module '@fortawesome/fontawesome-free-brands/faEdge.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faEdge'>;
}
declare module '@fortawesome/fontawesome-free-brands/faElementor.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faElementor'>;
}
declare module '@fortawesome/fontawesome-free-brands/faEmber.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faEmber'>;
}
declare module '@fortawesome/fontawesome-free-brands/faEmpire.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faEmpire'>;
}
declare module '@fortawesome/fontawesome-free-brands/faEnvira.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faEnvira'>;
}
declare module '@fortawesome/fontawesome-free-brands/faErlang.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faErlang'>;
}
declare module '@fortawesome/fontawesome-free-brands/faEthereum.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faEthereum'>;
}
declare module '@fortawesome/fontawesome-free-brands/faEtsy.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faEtsy'>;
}
declare module '@fortawesome/fontawesome-free-brands/faExpeditedssl.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faExpeditedssl'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFacebook.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFacebook'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFacebookF.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFacebookF'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFacebookMessenger.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFacebookMessenger'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFacebookSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFacebookSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFirefox.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFirefox'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFirstdraft.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFirstdraft'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFirstOrder.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFirstOrder'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFirstOrderAlt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFirstOrderAlt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFlickr.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFlickr'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFlipboard.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFlipboard'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFly.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFly'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFontAwesome.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFontAwesome'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFontAwesomeAlt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFontAwesomeAlt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFontAwesomeFlag.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFontAwesomeFlag'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFontAwesomeLogoFull.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFontAwesomeLogoFull'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFonticons.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFonticons'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFonticonsFi.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFonticonsFi'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFortAwesome.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFortAwesome'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFortAwesomeAlt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFortAwesomeAlt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faForumbee.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faForumbee'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFoursquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFoursquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFreebsd.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFreebsd'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFreeCodeCamp.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFreeCodeCamp'>;
}
declare module '@fortawesome/fontawesome-free-brands/faFulcrum.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faFulcrum'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGalacticRepublic.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGalacticRepublic'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGalacticSenate.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGalacticSenate'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGetPocket.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGetPocket'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGg.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGg'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGgCircle.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGgCircle'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGit.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGit'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGithub.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGithub'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGithubAlt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGithubAlt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGithubSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGithubSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGitkraken.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGitkraken'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGitlab.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGitlab'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGitSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGitSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGitter.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGitter'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGlide.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGlide'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGlideG.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGlideG'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGofore.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGofore'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGoodreads.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGoodreads'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGoodreadsG.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGoodreadsG'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGoogle.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGoogle'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGoogleDrive.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGoogleDrive'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGooglePlay.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGooglePlay'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGooglePlus.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGooglePlus'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGooglePlusG.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGooglePlusG'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGooglePlusSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGooglePlusSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGoogleWallet.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGoogleWallet'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGratipay.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGratipay'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGrav.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGrav'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGripfire.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGripfire'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGrunt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGrunt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faGulp.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faGulp'>;
}
declare module '@fortawesome/fontawesome-free-brands/faHackerNews.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faHackerNews'>;
}
declare module '@fortawesome/fontawesome-free-brands/faHackerNewsSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faHackerNewsSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faHips.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faHips'>;
}
declare module '@fortawesome/fontawesome-free-brands/faHireAHelper.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faHireAHelper'>;
}
declare module '@fortawesome/fontawesome-free-brands/faHooli.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faHooli'>;
}
declare module '@fortawesome/fontawesome-free-brands/faHotjar.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faHotjar'>;
}
declare module '@fortawesome/fontawesome-free-brands/faHouzz.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faHouzz'>;
}
declare module '@fortawesome/fontawesome-free-brands/faHtml5.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faHtml5'>;
}
declare module '@fortawesome/fontawesome-free-brands/faHubspot.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faHubspot'>;
}
declare module '@fortawesome/fontawesome-free-brands/faImdb.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faImdb'>;
}
declare module '@fortawesome/fontawesome-free-brands/faInstagram.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faInstagram'>;
}
declare module '@fortawesome/fontawesome-free-brands/faInternetExplorer.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faInternetExplorer'>;
}
declare module '@fortawesome/fontawesome-free-brands/faIoxhost.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faIoxhost'>;
}
declare module '@fortawesome/fontawesome-free-brands/faItunes.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faItunes'>;
}
declare module '@fortawesome/fontawesome-free-brands/faItunesNote.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faItunesNote'>;
}
declare module '@fortawesome/fontawesome-free-brands/faJava.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faJava'>;
}
declare module '@fortawesome/fontawesome-free-brands/faJediOrder.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faJediOrder'>;
}
declare module '@fortawesome/fontawesome-free-brands/faJenkins.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faJenkins'>;
}
declare module '@fortawesome/fontawesome-free-brands/faJoget.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faJoget'>;
}
declare module '@fortawesome/fontawesome-free-brands/faJoomla.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faJoomla'>;
}
declare module '@fortawesome/fontawesome-free-brands/faJs.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faJs'>;
}
declare module '@fortawesome/fontawesome-free-brands/faJsfiddle.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faJsfiddle'>;
}
declare module '@fortawesome/fontawesome-free-brands/faJsSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faJsSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faKeybase.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faKeybase'>;
}
declare module '@fortawesome/fontawesome-free-brands/faKeycdn.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faKeycdn'>;
}
declare module '@fortawesome/fontawesome-free-brands/faKickstarter.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faKickstarter'>;
}
declare module '@fortawesome/fontawesome-free-brands/faKickstarterK.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faKickstarterK'>;
}
declare module '@fortawesome/fontawesome-free-brands/faKorvue.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faKorvue'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLaravel.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLaravel'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLastfm.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLastfm'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLastfmSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLastfmSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLeanpub.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLeanpub'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLess.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLess'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLine.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLine'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLinkedin.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLinkedin'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLinkedinIn.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLinkedinIn'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLinode.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLinode'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLinux.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLinux'>;
}
declare module '@fortawesome/fontawesome-free-brands/faLyft.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faLyft'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMagento.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMagento'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMandalorian.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMandalorian'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMastodon.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMastodon'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMaxcdn.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMaxcdn'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMedapps.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMedapps'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMedium.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMedium'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMediumM.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMediumM'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMedrt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMedrt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMeetup.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMeetup'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMicrosoft.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMicrosoft'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMix.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMix'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMixcloud.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMixcloud'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMizuni.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMizuni'>;
}
declare module '@fortawesome/fontawesome-free-brands/faModx.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faModx'>;
}
declare module '@fortawesome/fontawesome-free-brands/faMonero.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faMonero'>;
}
declare module '@fortawesome/fontawesome-free-brands/faNapster.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faNapster'>;
}
declare module '@fortawesome/fontawesome-free-brands/faNintendoSwitch.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faNintendoSwitch'>;
}
declare module '@fortawesome/fontawesome-free-brands/faNode.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faNode'>;
}
declare module '@fortawesome/fontawesome-free-brands/faNodeJs.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faNodeJs'>;
}
declare module '@fortawesome/fontawesome-free-brands/faNpm.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faNpm'>;
}
declare module '@fortawesome/fontawesome-free-brands/faNs8.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faNs8'>;
}
declare module '@fortawesome/fontawesome-free-brands/faNutritionix.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faNutritionix'>;
}
declare module '@fortawesome/fontawesome-free-brands/faOdnoklassniki.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faOdnoklassniki'>;
}
declare module '@fortawesome/fontawesome-free-brands/faOdnoklassnikiSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faOdnoklassnikiSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faOldRepublic.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faOldRepublic'>;
}
declare module '@fortawesome/fontawesome-free-brands/faOpencart.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faOpencart'>;
}
declare module '@fortawesome/fontawesome-free-brands/faOpenid.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faOpenid'>;
}
declare module '@fortawesome/fontawesome-free-brands/faOpera.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faOpera'>;
}
declare module '@fortawesome/fontawesome-free-brands/faOptinMonster.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faOptinMonster'>;
}
declare module '@fortawesome/fontawesome-free-brands/faOsi.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faOsi'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPage4.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPage4'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPagelines.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPagelines'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPalfed.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPalfed'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPatreon.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPatreon'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPaypal.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPaypal'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPeriscope.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPeriscope'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPhabricator.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPhabricator'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPhoenixFramework.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPhoenixFramework'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPhoenixSquadron.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPhoenixSquadron'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPhp.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPhp'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPiedPiper.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPiedPiper'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPiedPiperAlt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPiedPiperAlt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPiedPiperHat.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPiedPiperHat'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPiedPiperPp.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPiedPiperPp'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPinterest.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPinterest'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPinterestP.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPinterestP'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPinterestSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPinterestSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPlaystation.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPlaystation'>;
}
declare module '@fortawesome/fontawesome-free-brands/faProductHunt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faProductHunt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPushed.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPushed'>;
}
declare module '@fortawesome/fontawesome-free-brands/faPython.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faPython'>;
}
declare module '@fortawesome/fontawesome-free-brands/faQq.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faQq'>;
}
declare module '@fortawesome/fontawesome-free-brands/faQuinscape.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faQuinscape'>;
}
declare module '@fortawesome/fontawesome-free-brands/faQuora.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faQuora'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRavelry.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRavelry'>;
}
declare module '@fortawesome/fontawesome-free-brands/faReact.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faReact'>;
}
declare module '@fortawesome/fontawesome-free-brands/faReadme.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faReadme'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRebel.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRebel'>;
}
declare module '@fortawesome/fontawesome-free-brands/faReddit.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faReddit'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRedditAlien.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRedditAlien'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRedditSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRedditSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRedRiver.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRedRiver'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRendact.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRendact'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRenren.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRenren'>;
}
declare module '@fortawesome/fontawesome-free-brands/faReplyd.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faReplyd'>;
}
declare module '@fortawesome/fontawesome-free-brands/faResearchgate.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faResearchgate'>;
}
declare module '@fortawesome/fontawesome-free-brands/faResolving.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faResolving'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRocketchat.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRocketchat'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRockrms.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRockrms'>;
}
declare module '@fortawesome/fontawesome-free-brands/faRProject.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faRProject'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSafari.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSafari'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSass.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSass'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSchlix.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSchlix'>;
}
declare module '@fortawesome/fontawesome-free-brands/faScribd.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faScribd'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSearchengin.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSearchengin'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSellcast.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSellcast'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSellsy.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSellsy'>;
}
declare module '@fortawesome/fontawesome-free-brands/faServicestack.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faServicestack'>;
}
declare module '@fortawesome/fontawesome-free-brands/faShirtsinbulk.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faShirtsinbulk'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSimplybuilt.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSimplybuilt'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSistrix.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSistrix'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSith.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSith'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSkyatlas.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSkyatlas'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSkype.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSkype'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSlack.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSlack'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSlackHash.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSlackHash'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSlideshare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSlideshare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSnapchat.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSnapchat'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSnapchatGhost.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSnapchatGhost'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSnapchatSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSnapchatSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSoundcloud.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSoundcloud'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSpeakap.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSpeakap'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSpotify.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSpotify'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStackExchange.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStackExchange'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStackOverflow.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStackOverflow'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStaylinked.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStaylinked'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSteam.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSteam'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSteamSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSteamSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSteamSymbol.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSteamSymbol'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStickerMule.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStickerMule'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStrava.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStrava'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStripe.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStripe'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStripeS.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStripeS'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStudiovinari.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStudiovinari'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStumbleupon.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStumbleupon'>;
}
declare module '@fortawesome/fontawesome-free-brands/faStumbleuponCircle.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faStumbleuponCircle'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSuperpowers.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSuperpowers'>;
}
declare module '@fortawesome/fontawesome-free-brands/faSupple.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faSupple'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTeamspeak.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTeamspeak'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTelegram.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTelegram'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTelegramPlane.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTelegramPlane'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTencentWeibo.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTencentWeibo'>;
}
declare module '@fortawesome/fontawesome-free-brands/faThemeisle.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faThemeisle'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTradeFederation.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTradeFederation'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTrello.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTrello'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTripadvisor.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTripadvisor'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTumblr.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTumblr'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTumblrSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTumblrSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTwitch.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTwitch'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTwitter.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTwitter'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTwitterSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTwitterSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faTypo3.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faTypo3'>;
}
declare module '@fortawesome/fontawesome-free-brands/faUber.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faUber'>;
}
declare module '@fortawesome/fontawesome-free-brands/faUikit.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faUikit'>;
}
declare module '@fortawesome/fontawesome-free-brands/faUniregistry.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faUniregistry'>;
}
declare module '@fortawesome/fontawesome-free-brands/faUntappd.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faUntappd'>;
}
declare module '@fortawesome/fontawesome-free-brands/faUsb.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faUsb'>;
}
declare module '@fortawesome/fontawesome-free-brands/faUssunnah.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faUssunnah'>;
}
declare module '@fortawesome/fontawesome-free-brands/faVaadin.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faVaadin'>;
}
declare module '@fortawesome/fontawesome-free-brands/faViacoin.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faViacoin'>;
}
declare module '@fortawesome/fontawesome-free-brands/faViadeo.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faViadeo'>;
}
declare module '@fortawesome/fontawesome-free-brands/faViadeoSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faViadeoSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faViber.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faViber'>;
}
declare module '@fortawesome/fontawesome-free-brands/faVimeo.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faVimeo'>;
}
declare module '@fortawesome/fontawesome-free-brands/faVimeoSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faVimeoSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faVimeoV.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faVimeoV'>;
}
declare module '@fortawesome/fontawesome-free-brands/faVine.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faVine'>;
}
declare module '@fortawesome/fontawesome-free-brands/faVk.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faVk'>;
}
declare module '@fortawesome/fontawesome-free-brands/faVnv.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faVnv'>;
}
declare module '@fortawesome/fontawesome-free-brands/faVuejs.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faVuejs'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWeibo.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWeibo'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWeixin.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWeixin'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWhatsapp.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWhatsapp'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWhatsappSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWhatsappSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWhmcs.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWhmcs'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWikipediaW.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWikipediaW'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWindows.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWindows'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWolfPackBattalion.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWolfPackBattalion'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWordpress.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWordpress'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWordpressSimple.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWordpressSimple'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWpbeginner.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWpbeginner'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWpexplorer.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWpexplorer'>;
}
declare module '@fortawesome/fontawesome-free-brands/faWpforms.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faWpforms'>;
}
declare module '@fortawesome/fontawesome-free-brands/faXbox.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faXbox'>;
}
declare module '@fortawesome/fontawesome-free-brands/faXing.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faXing'>;
}
declare module '@fortawesome/fontawesome-free-brands/faXingSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faXingSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/faYahoo.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faYahoo'>;
}
declare module '@fortawesome/fontawesome-free-brands/faYandex.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faYandex'>;
}
declare module '@fortawesome/fontawesome-free-brands/faYandexInternational.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faYandexInternational'>;
}
declare module '@fortawesome/fontawesome-free-brands/faYCombinator.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faYCombinator'>;
}
declare module '@fortawesome/fontawesome-free-brands/faYelp.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faYelp'>;
}
declare module '@fortawesome/fontawesome-free-brands/faYoast.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faYoast'>;
}
declare module '@fortawesome/fontawesome-free-brands/faYoutube.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faYoutube'>;
}
declare module '@fortawesome/fontawesome-free-brands/faYoutubeSquare.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/faYoutubeSquare'>;
}
declare module '@fortawesome/fontawesome-free-brands/index.es.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/index.es'>;
}
declare module '@fortawesome/fontawesome-free-brands/index' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands'>;
}
declare module '@fortawesome/fontawesome-free-brands/index.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands'>;
}
declare module '@fortawesome/fontawesome-free-brands/shakable.es.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/shakable.es'>;
}
declare module '@fortawesome/fontawesome-free-brands/shakable.js' {
  declare module.exports: $Exports<'@fortawesome/fontawesome-free-brands/shakable'>;
}
