// flow-typed signature: bda261b473998beedd6a9ece5906f016
// flow-typed version: <<STUB>>/react-controllables_v0.6.0/flow_v0.99.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-controllables'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-controllables' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-controllables/gulpfile.babel' {
  declare module.exports: any;
}

declare module 'react-controllables/lib/index' {
  declare module.exports: any;
}

declare module 'react-controllables/lib/mixin' {
  declare module.exports: any;
}

declare module 'react-controllables/lib/standalone' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-controllables/gulpfile.babel.js' {
  declare module.exports: $Exports<'react-controllables/gulpfile.babel'>;
}
declare module 'react-controllables/lib/index.js' {
  declare module.exports: $Exports<'react-controllables/lib/index'>;
}
declare module 'react-controllables/lib/mixin.js' {
  declare module.exports: $Exports<'react-controllables/lib/mixin'>;
}
declare module 'react-controllables/lib/standalone.js' {
  declare module.exports: $Exports<'react-controllables/lib/standalone'>;
}
