// @flow
/* eslint-disable */

// flow-typed signature: 66e094f5a4033c8247e0f7c861ad9d04
// flow-typed version: <<STUB>>/@material-ui/styles_v4.0.1/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@material-ui/styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@material-ui/styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@material-ui/styles/createGenerateClassName/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@material-ui/styles/createGenerateClassName/createGenerateClassNameHash' {
  declare module.exports: any;
}

declare module '@material-ui/styles/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@material-ui/styles/createGenerateClassName/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/createStyles/createStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/createStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/createStyles/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/createGenerateClassName/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/createGenerateClassName/createGenerateClassNameHash' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/createGenerateClassName/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/createStyles/createStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/createStyles/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/getStylesCreator/getStylesCreator' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/getStylesCreator/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/getStylesCreator/noopTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/getThemeProps/getThemeProps' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/getThemeProps/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/jssPreset/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/jssPreset/jssPreset' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/makeStyles/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/makeStyles/indexCounter' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/makeStyles/makeStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/makeStyles/multiKeyStore' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/mergeClasses/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/mergeClasses/mergeClasses' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/ServerStyleSheets/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/ServerStyleSheets/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/styled/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/styled/styled' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/StylesProvider/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/StylesProvider/StylesProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/ThemeProvider/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/ThemeProvider/nested' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/ThemeProvider/ThemeProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/useTheme/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/useTheme/ThemeContext' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/useTheme/useTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/withStyles/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/withStyles/withStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/withTheme/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/es/withTheme/withTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/createGenerateClassName/createGenerateClassName' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/createGenerateClassName/createGenerateClassNameHash' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/createGenerateClassName/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/createStyles/createStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/createStyles/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/getStylesCreator/getStylesCreator' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/getStylesCreator/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/getStylesCreator/noopTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/getThemeProps/getThemeProps' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/getThemeProps/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/jssPreset/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/jssPreset/jssPreset' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/makeStyles/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/makeStyles/indexCounter' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/makeStyles/makeStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/makeStyles/multiKeyStore' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/mergeClasses/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/mergeClasses/mergeClasses' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/ServerStyleSheets/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/ServerStyleSheets/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/styled/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/styled/styled' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/StylesProvider/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/StylesProvider/StylesProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/ThemeProvider/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/ThemeProvider/nested' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/ThemeProvider/ThemeProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/useTheme/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/useTheme/ThemeContext' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/useTheme/useTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/withStyles/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/withStyles/withStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/withTheme/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/esm/withTheme/withTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/getStylesCreator/getStylesCreator' {
  declare module.exports: any;
}

declare module '@material-ui/styles/getStylesCreator' {
  declare module.exports: any;
}

declare module '@material-ui/styles/getStylesCreator/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/getStylesCreator/noopTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/getThemeProps/getThemeProps' {
  declare module.exports: any;
}

declare module '@material-ui/styles/getThemeProps' {
  declare module.exports: any;
}

declare module '@material-ui/styles/getThemeProps/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/jssPreset' {
  declare module.exports: any;
}

declare module '@material-ui/styles/jssPreset/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/jssPreset/jssPreset' {
  declare module.exports: any;
}

declare module '@material-ui/styles/makeStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/makeStyles/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/makeStyles/indexCounter' {
  declare module.exports: any;
}

declare module '@material-ui/styles/makeStyles/makeStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/makeStyles/multiKeyStore' {
  declare module.exports: any;
}

declare module '@material-ui/styles/mergeClasses' {
  declare module.exports: any;
}

declare module '@material-ui/styles/mergeClasses/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/mergeClasses/mergeClasses' {
  declare module.exports: any;
}

declare module '@material-ui/styles/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@material-ui/styles/ServerStyleSheets/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/ServerStyleSheets/ServerStyleSheets' {
  declare module.exports: any;
}

declare module '@material-ui/styles/styled' {
  declare module.exports: any;
}

declare module '@material-ui/styles/styled/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/styled/styled' {
  declare module.exports: any;
}

declare module '@material-ui/styles/StylesProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/StylesProvider/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/StylesProvider/StylesProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/ThemeProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/ThemeProvider/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/ThemeProvider/nested' {
  declare module.exports: any;
}

declare module '@material-ui/styles/ThemeProvider/ThemeProvider' {
  declare module.exports: any;
}

declare module '@material-ui/styles/useTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/useTheme/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/useTheme/ThemeContext' {
  declare module.exports: any;
}

declare module '@material-ui/styles/useTheme/useTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/withStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/withStyles/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/withStyles/withStyles' {
  declare module.exports: any;
}

declare module '@material-ui/styles/withTheme' {
  declare module.exports: any;
}

declare module '@material-ui/styles/withTheme/index' {
  declare module.exports: any;
}

declare module '@material-ui/styles/withTheme/withTheme' {
  declare module.exports: any;
}

// Filename aliases
declare module '@material-ui/styles/createGenerateClassName/createGenerateClassName.js' {
  declare module.exports: $Exports<'@material-ui/styles/createGenerateClassName/createGenerateClassName'>;
}
declare module '@material-ui/styles/createGenerateClassName/createGenerateClassNameHash.js' {
  declare module.exports: $Exports<'@material-ui/styles/createGenerateClassName/createGenerateClassNameHash'>;
}
declare module '@material-ui/styles/createGenerateClassName/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/createGenerateClassName/index'>;
}
declare module '@material-ui/styles/createStyles/createStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/createStyles/createStyles'>;
}
declare module '@material-ui/styles/createStyles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/createStyles/index'>;
}
declare module '@material-ui/styles/es/createGenerateClassName/createGenerateClassName.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/createGenerateClassName/createGenerateClassName'>;
}
declare module '@material-ui/styles/es/createGenerateClassName/createGenerateClassNameHash.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/createGenerateClassName/createGenerateClassNameHash'>;
}
declare module '@material-ui/styles/es/createGenerateClassName/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/createGenerateClassName/index'>;
}
declare module '@material-ui/styles/es/createStyles/createStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/createStyles/createStyles'>;
}
declare module '@material-ui/styles/es/createStyles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/createStyles/index'>;
}
declare module '@material-ui/styles/es/getStylesCreator/getStylesCreator.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/getStylesCreator/getStylesCreator'>;
}
declare module '@material-ui/styles/es/getStylesCreator/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/getStylesCreator/index'>;
}
declare module '@material-ui/styles/es/getStylesCreator/noopTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/getStylesCreator/noopTheme'>;
}
declare module '@material-ui/styles/es/getThemeProps/getThemeProps.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/getThemeProps/getThemeProps'>;
}
declare module '@material-ui/styles/es/getThemeProps/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/getThemeProps/index'>;
}
declare module '@material-ui/styles/es/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/index'>;
}
declare module '@material-ui/styles/es/jssPreset/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/jssPreset/index'>;
}
declare module '@material-ui/styles/es/jssPreset/jssPreset.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/jssPreset/jssPreset'>;
}
declare module '@material-ui/styles/es/makeStyles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/makeStyles/index'>;
}
declare module '@material-ui/styles/es/makeStyles/indexCounter.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/makeStyles/indexCounter'>;
}
declare module '@material-ui/styles/es/makeStyles/makeStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/makeStyles/makeStyles'>;
}
declare module '@material-ui/styles/es/makeStyles/multiKeyStore.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/makeStyles/multiKeyStore'>;
}
declare module '@material-ui/styles/es/mergeClasses/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/mergeClasses/index'>;
}
declare module '@material-ui/styles/es/mergeClasses/mergeClasses.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/mergeClasses/mergeClasses'>;
}
declare module '@material-ui/styles/es/ServerStyleSheets/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/ServerStyleSheets/index'>;
}
declare module '@material-ui/styles/es/ServerStyleSheets/ServerStyleSheets.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/ServerStyleSheets/ServerStyleSheets'>;
}
declare module '@material-ui/styles/es/styled/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/styled/index'>;
}
declare module '@material-ui/styles/es/styled/styled.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/styled/styled'>;
}
declare module '@material-ui/styles/es/StylesProvider/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/StylesProvider/index'>;
}
declare module '@material-ui/styles/es/StylesProvider/StylesProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/StylesProvider/StylesProvider'>;
}
declare module '@material-ui/styles/es/ThemeProvider/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/ThemeProvider/index'>;
}
declare module '@material-ui/styles/es/ThemeProvider/nested.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/ThemeProvider/nested'>;
}
declare module '@material-ui/styles/es/ThemeProvider/ThemeProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/ThemeProvider/ThemeProvider'>;
}
declare module '@material-ui/styles/es/useTheme/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/useTheme/index'>;
}
declare module '@material-ui/styles/es/useTheme/ThemeContext.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/useTheme/ThemeContext'>;
}
declare module '@material-ui/styles/es/useTheme/useTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/useTheme/useTheme'>;
}
declare module '@material-ui/styles/es/withStyles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/withStyles/index'>;
}
declare module '@material-ui/styles/es/withStyles/withStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/withStyles/withStyles'>;
}
declare module '@material-ui/styles/es/withTheme/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/withTheme/index'>;
}
declare module '@material-ui/styles/es/withTheme/withTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/es/withTheme/withTheme'>;
}
declare module '@material-ui/styles/esm/createGenerateClassName/createGenerateClassName.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/createGenerateClassName/createGenerateClassName'>;
}
declare module '@material-ui/styles/esm/createGenerateClassName/createGenerateClassNameHash.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/createGenerateClassName/createGenerateClassNameHash'>;
}
declare module '@material-ui/styles/esm/createGenerateClassName/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/createGenerateClassName/index'>;
}
declare module '@material-ui/styles/esm/createStyles/createStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/createStyles/createStyles'>;
}
declare module '@material-ui/styles/esm/createStyles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/createStyles/index'>;
}
declare module '@material-ui/styles/esm/getStylesCreator/getStylesCreator.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/getStylesCreator/getStylesCreator'>;
}
declare module '@material-ui/styles/esm/getStylesCreator/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/getStylesCreator/index'>;
}
declare module '@material-ui/styles/esm/getStylesCreator/noopTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/getStylesCreator/noopTheme'>;
}
declare module '@material-ui/styles/esm/getThemeProps/getThemeProps.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/getThemeProps/getThemeProps'>;
}
declare module '@material-ui/styles/esm/getThemeProps/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/getThemeProps/index'>;
}
declare module '@material-ui/styles/esm/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/index'>;
}
declare module '@material-ui/styles/esm/jssPreset/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/jssPreset/index'>;
}
declare module '@material-ui/styles/esm/jssPreset/jssPreset.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/jssPreset/jssPreset'>;
}
declare module '@material-ui/styles/esm/makeStyles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/makeStyles/index'>;
}
declare module '@material-ui/styles/esm/makeStyles/indexCounter.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/makeStyles/indexCounter'>;
}
declare module '@material-ui/styles/esm/makeStyles/makeStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/makeStyles/makeStyles'>;
}
declare module '@material-ui/styles/esm/makeStyles/multiKeyStore.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/makeStyles/multiKeyStore'>;
}
declare module '@material-ui/styles/esm/mergeClasses/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/mergeClasses/index'>;
}
declare module '@material-ui/styles/esm/mergeClasses/mergeClasses.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/mergeClasses/mergeClasses'>;
}
declare module '@material-ui/styles/esm/ServerStyleSheets/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/ServerStyleSheets/index'>;
}
declare module '@material-ui/styles/esm/ServerStyleSheets/ServerStyleSheets.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/ServerStyleSheets/ServerStyleSheets'>;
}
declare module '@material-ui/styles/esm/styled/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/styled/index'>;
}
declare module '@material-ui/styles/esm/styled/styled.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/styled/styled'>;
}
declare module '@material-ui/styles/esm/StylesProvider/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/StylesProvider/index'>;
}
declare module '@material-ui/styles/esm/StylesProvider/StylesProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/StylesProvider/StylesProvider'>;
}
declare module '@material-ui/styles/esm/ThemeProvider/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/ThemeProvider/index'>;
}
declare module '@material-ui/styles/esm/ThemeProvider/nested.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/ThemeProvider/nested'>;
}
declare module '@material-ui/styles/esm/ThemeProvider/ThemeProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/ThemeProvider/ThemeProvider'>;
}
declare module '@material-ui/styles/esm/useTheme/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/useTheme/index'>;
}
declare module '@material-ui/styles/esm/useTheme/ThemeContext.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/useTheme/ThemeContext'>;
}
declare module '@material-ui/styles/esm/useTheme/useTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/useTheme/useTheme'>;
}
declare module '@material-ui/styles/esm/withStyles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/withStyles/index'>;
}
declare module '@material-ui/styles/esm/withStyles/withStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/withStyles/withStyles'>;
}
declare module '@material-ui/styles/esm/withTheme/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/withTheme/index'>;
}
declare module '@material-ui/styles/esm/withTheme/withTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/esm/withTheme/withTheme'>;
}
declare module '@material-ui/styles/getStylesCreator/getStylesCreator.js' {
  declare module.exports: $Exports<'@material-ui/styles/getStylesCreator/getStylesCreator'>;
}
declare module '@material-ui/styles/getStylesCreator/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/getStylesCreator/index'>;
}
declare module '@material-ui/styles/getStylesCreator/noopTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/getStylesCreator/noopTheme'>;
}
declare module '@material-ui/styles/getThemeProps/getThemeProps.js' {
  declare module.exports: $Exports<'@material-ui/styles/getThemeProps/getThemeProps'>;
}
declare module '@material-ui/styles/getThemeProps/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/getThemeProps/index'>;
}
declare module '@material-ui/styles/index' {
  declare module.exports: $Exports<'@material-ui/styles'>;
}
declare module '@material-ui/styles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles'>;
}
declare module '@material-ui/styles/jssPreset/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/jssPreset/index'>;
}
declare module '@material-ui/styles/jssPreset/jssPreset.js' {
  declare module.exports: $Exports<'@material-ui/styles/jssPreset/jssPreset'>;
}
declare module '@material-ui/styles/makeStyles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/makeStyles/index'>;
}
declare module '@material-ui/styles/makeStyles/indexCounter.js' {
  declare module.exports: $Exports<'@material-ui/styles/makeStyles/indexCounter'>;
}
declare module '@material-ui/styles/makeStyles/makeStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/makeStyles/makeStyles'>;
}
declare module '@material-ui/styles/makeStyles/multiKeyStore.js' {
  declare module.exports: $Exports<'@material-ui/styles/makeStyles/multiKeyStore'>;
}
declare module '@material-ui/styles/mergeClasses/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/mergeClasses/index'>;
}
declare module '@material-ui/styles/mergeClasses/mergeClasses.js' {
  declare module.exports: $Exports<'@material-ui/styles/mergeClasses/mergeClasses'>;
}
declare module '@material-ui/styles/ServerStyleSheets/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/ServerStyleSheets/index'>;
}
declare module '@material-ui/styles/ServerStyleSheets/ServerStyleSheets.js' {
  declare module.exports: $Exports<'@material-ui/styles/ServerStyleSheets/ServerStyleSheets'>;
}
declare module '@material-ui/styles/styled/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/styled/index'>;
}
declare module '@material-ui/styles/styled/styled.js' {
  declare module.exports: $Exports<'@material-ui/styles/styled/styled'>;
}
declare module '@material-ui/styles/StylesProvider/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/StylesProvider/index'>;
}
declare module '@material-ui/styles/StylesProvider/StylesProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/StylesProvider/StylesProvider'>;
}
declare module '@material-ui/styles/ThemeProvider/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/ThemeProvider/index'>;
}
declare module '@material-ui/styles/ThemeProvider/nested.js' {
  declare module.exports: $Exports<'@material-ui/styles/ThemeProvider/nested'>;
}
declare module '@material-ui/styles/ThemeProvider/ThemeProvider.js' {
  declare module.exports: $Exports<'@material-ui/styles/ThemeProvider/ThemeProvider'>;
}
declare module '@material-ui/styles/useTheme/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/useTheme/index'>;
}
declare module '@material-ui/styles/useTheme/ThemeContext.js' {
  declare module.exports: $Exports<'@material-ui/styles/useTheme/ThemeContext'>;
}
declare module '@material-ui/styles/useTheme/useTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/useTheme/useTheme'>;
}
declare module '@material-ui/styles/withStyles/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/withStyles/index'>;
}
declare module '@material-ui/styles/withStyles/withStyles.js' {
  declare module.exports: $Exports<'@material-ui/styles/withStyles/withStyles'>;
}
declare module '@material-ui/styles/withTheme/index.js' {
  declare module.exports: $Exports<'@material-ui/styles/withTheme/index'>;
}
declare module '@material-ui/styles/withTheme/withTheme.js' {
  declare module.exports: $Exports<'@material-ui/styles/withTheme/withTheme'>;
}
