// @flow
// flow-typed signature: 6ce384743360218ca71361a72817cdb8
// flow-typed version: <<STUB>>/gatsby-image_v2.0.29/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gatsby-image'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gatsby-image' {
  declare interface FixedObject {
    width: number;
    height: number;
    src: string;
    srcSet: string;
    base64?: string;
    tracedSVG?: string;
    srcWebp?: string;
    srcSetWebp?: string;
  }

  declare interface FluidObject {
    aspectRatio: number;
    src: string;
    srcSet: string;
    sizes: string;
    base64?: string;
    tracedSVG?: string;
    srcWebp?: string;
    srcSetWebp?: string;
  }

  declare interface GatsbyImageProps {
    resolutions?: FixedObject;
    sizes?: FluidObject;
    fixed?: FixedObject;
    fluid?: FluidObject;
    fadeIn?: boolean;
    title?: string;
    alt?: string;
    className?: string | {};
    critical?: boolean;
    crossOrigin?: string | boolean;
    style?: {};
    imgStyle?: {};
    placeholderStyle?: {};
    backgroundColor?: string | boolean;
    onLoad?: () => void;
    onStartLoad?: (param: { wasCached: boolean }) => void;
    onError?: (event: any) => void;
    Tag?: string;
    itemProp?: string;
  }

  declare export default class GatsbyImage extends React$Component<
    GatsbyImageProps,
    any,
  > {}
}
