// @flow
// Hack this package should have its own Flow types...
// 
// flow-typed signature: 2575a8af1c3c260ac5bd6b4056f550f3
// flow-typed version: <<STUB>>/material-ui-layout_v1.0.0/flow_v0.91.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'material-ui-layout'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'material-ui-layout' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'material-ui-layout/flow-typed/npm/@material-ui/core_v1.x.x' {
  declare module.exports: any;
}

declare module 'material-ui-layout/flow-typed/npm/classnames_v2.x.x' {
  declare module.exports: any;
}

declare module 'material-ui-layout/flow-typed/npm/lodash_v4.x.x' {
  declare module.exports: any;
}

declare module 'material-ui-layout/flow-typed/npm/recompose_v0.x.x' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/AppBar/AppBar' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/AppBar/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/AppBar/styles' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/Footer/Footer' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/Footer/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/Footer/styles' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/Layout/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/Layout/Layout' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/Layout/LayoutActions' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/components/Layout/styles' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/AppBar/BasicAppBar/BasicAppBar' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/AppBar/BasicAppBar/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/AppBar/BasicAppBar' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/AppBar/BasicAppBar/styles' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar/styles' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar/TwoRowsAppBar' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/BasicDrawer/BasicDrawer' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/BasicDrawer' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/BasicDrawer/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/BasicDrawer/styles' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/DrawerItemsList/DrawerItem' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/DrawerItemsList/DrawerItemsList' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/DrawerItemsList' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/DrawerItemsList/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/DrawerItemsList/styles' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/StandardDrawer' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/StandardDrawer/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/StandardDrawer/StandardDrawer' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Drawer/StandardDrawer/styles' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Footer/BasicFooter/BasicFooter' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Footer/BasicFooter' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Footer/BasicFooter/index' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/templates/Footer/BasicFooter/styles' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/types/Classes' {
  declare module.exports: any;
}

declare module 'material-ui-layout/lib/types/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'material-ui-layout/flow-typed/npm/@material-ui/core_v1.x.x.js' {
  declare module.exports: $Exports<'material-ui-layout/flow-typed/npm/@material-ui/core_v1.x.x'>;
}
declare module 'material-ui-layout/flow-typed/npm/classnames_v2.x.x.js' {
  declare module.exports: $Exports<'material-ui-layout/flow-typed/npm/classnames_v2.x.x'>;
}
declare module 'material-ui-layout/flow-typed/npm/lodash_v4.x.x.js' {
  declare module.exports: $Exports<'material-ui-layout/flow-typed/npm/lodash_v4.x.x'>;
}
declare module 'material-ui-layout/flow-typed/npm/recompose_v0.x.x.js' {
  declare module.exports: $Exports<'material-ui-layout/flow-typed/npm/recompose_v0.x.x'>;
}
declare module 'material-ui-layout/lib/components/AppBar/AppBar.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/AppBar/AppBar'>;
}
declare module 'material-ui-layout/lib/components/AppBar/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/AppBar/index'>;
}
declare module 'material-ui-layout/lib/components/AppBar/styles.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/AppBar/styles'>;
}
declare module 'material-ui-layout/lib/components/Footer/Footer.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/Footer/Footer'>;
}
declare module 'material-ui-layout/lib/components/Footer/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/Footer/index'>;
}
declare module 'material-ui-layout/lib/components/Footer/styles.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/Footer/styles'>;
}
declare module 'material-ui-layout/lib/components/Layout/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/Layout/index'>;
}
declare module 'material-ui-layout/lib/components/Layout/Layout.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/Layout/Layout'>;
}
declare module 'material-ui-layout/lib/components/Layout/LayoutActions.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/Layout/LayoutActions'>;
}
declare module 'material-ui-layout/lib/components/Layout/styles.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/components/Layout/styles'>;
}
declare module 'material-ui-layout/lib/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/index'>;
}
declare module 'material-ui-layout/lib/templates/AppBar/BasicAppBar/BasicAppBar.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/AppBar/BasicAppBar/BasicAppBar'>;
}
declare module 'material-ui-layout/lib/templates/AppBar/BasicAppBar/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/AppBar/BasicAppBar/index'>;
}
declare module 'material-ui-layout/lib/templates/AppBar/BasicAppBar/styles.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/AppBar/BasicAppBar/styles'>;
}
declare module 'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar/index'>;
}
declare module 'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar/styles.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar/styles'>;
}
declare module 'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar/TwoRowsAppBar.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/AppBar/TwoRowsAppBar/TwoRowsAppBar'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/BasicDrawer/BasicDrawer.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/BasicDrawer/BasicDrawer'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/BasicDrawer/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/BasicDrawer/index'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/BasicDrawer/styles.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/BasicDrawer/styles'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/DrawerItemsList/DrawerItem.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/DrawerItemsList/DrawerItem'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/DrawerItemsList/DrawerItemsList.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/DrawerItemsList/DrawerItemsList'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/DrawerItemsList/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/DrawerItemsList/index'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/DrawerItemsList/styles.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/DrawerItemsList/styles'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/StandardDrawer/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/StandardDrawer/index'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/StandardDrawer/StandardDrawer.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/StandardDrawer/StandardDrawer'>;
}
declare module 'material-ui-layout/lib/templates/Drawer/StandardDrawer/styles.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Drawer/StandardDrawer/styles'>;
}
declare module 'material-ui-layout/lib/templates/Footer/BasicFooter/BasicFooter.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Footer/BasicFooter/BasicFooter'>;
}
declare module 'material-ui-layout/lib/templates/Footer/BasicFooter/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Footer/BasicFooter/index'>;
}
declare module 'material-ui-layout/lib/templates/Footer/BasicFooter/styles.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/templates/Footer/BasicFooter/styles'>;
}
declare module 'material-ui-layout/lib/types/Classes.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/types/Classes'>;
}
declare module 'material-ui-layout/lib/types/index.js' {
  declare module.exports: $Exports<'material-ui-layout/lib/types/index'>;
}
